spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: LOGIN
    password: PASSWORD
  jpa:
    show-sql: true